### ISSUE TITLE
Release to CPAN

### ISSUE THREAD

**Issue by reneeb** [zakame/mojox-renderer-writeexcel#3]
Can you release version 2.04 on CPAN? It's still version 1.11 over there...

**Comment by zakame** [comment]
Hi reneeb!  The [MojoX::Renderer::WriteExcel][0] has been renamed now as [Mojolicious::Plugin::WriteExcel][1].  The MojoX module will no longer be updated.

[0]:  https://metacpan.org/pod/MojoX::Renderer::WriteExcel
[1]:  https://metacpan.org/pod/Mojolicious::Plugin::WriteExcel

**Comment by reneeb** [comment]
Thanks for the info. Then I will remove MojoX::Renderer::WriteExcel from http://mojo.perl-services.de

**Comment by zakame** [comment]
Thanks, too!  Great service for listing all the Mojo modules, BTW :+1:
