### ISSUE TITLE
Tests have started to fail (Mojolicious 9.25 ?)

### ISSUE THREAD

**Issue by andk** [zakame/mojox-renderer-writeexcel#5]
Diagnostics:
```
Mojo::Reactor::Poll: I/O watcher failed: A response has already been rendered
```
Sample fail report: http://www.cpantesters.org/cpan/report/92b9762a-ca73-11ec-9ce5-248179ec7e8a

Statistical analysis tells me that so far this failure only appears when Mojolicious version is 9.25.

**Comment by zakame** [comment]
Thanks @andk for the report!

Looks like the recent change in `Mojolicious::Renderer` is causing this: https://metacpan.org/release/SRI/Mojolicious-9.25/diff/SRI%2FMojolicious-9.24#lib/Mojolicious/Renderer.pm

We're likely due refactoring the implementation here - it has been several years!
